<a href="https://colab.research.google.com/github/mithra-malicious/carisurg_portfolio/blob/main/Tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(f"Pyhton version: {sys.version}")
print("Pandas version: ", pd.__version__)

Pyhton version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Pandas version:  2.2.2

In [12]:
FILE_PATH = '/content/drive/MyDrive/Copy of EmergencyTriageDataset_Reduced_Dirty.csv'

if not os.path.exists(FILE_PATH):
  path(f"ERROR: Cannot find the file! Make sure it is in: {os.getcwd()}")
else:
  df_raw= pd.read_csv(FILE_PATH)
  print(f"Data loaded successfully: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns")

  display(df_raw.head(10))

Data loaded successfully: 2205 rows x 11 columns

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [13]:
print("Unique values in Gender column:")
print(df_raw['Gender'].unique())

print("\nHow many of each variation exists:")
print(df_raw['Gender'].value_counts())

Unique values in Gender column:
['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

How many of each variation exists:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [15]:
gender_map = {
    'Male': 1,
    'MALE': 1,
    '1': 1,
    'Female': 0,
    'FEMALE': 0,
    '0': 0
}

df_raw['Gender_Clean'] = df_raw['Gender'].map(gender_map)

df_raw = df_raw.drop(columns=['Gender'])
df_raw = df_raw.rename(columns={'Gender_Clean': 'Gender'})

print("Cleaning pipeline complete!")

Cleaning pipeline complete!

In [16]:
print("---Final Verification---")
print(df_raw['Gender'].value_counts())
print(f"\nAny Missing (NaN) values left? {df_raw['Gender'].isnull().sum()}")
print(f"Final Data Tyep: {df_raw['Gender'].dtype}")

display(df_raw.head())

---Final Verification---
Series([], Name: count, dtype: int64)

Any Missing (NaN) values left? 2205
Final Data Tyep: float64

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0     NaN
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0     NaN
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0     NaN
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0     NaN
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0     NaN